### PR TITLE
Added NetConstruct menu module entry

### PR DESCRIPTION
**Pull request by chetanmistry**

### CODE REVIEW

**Comment by rshackleton** [comment]
@giorgioLUK the source code is not publicly available and we don't currently have a public facing product page or documentation for the module - is the `sourceUrl` parameter required or can we leave this out?

**Comment by rshackleton** [comment]
@giorgioLUK I've updated the icon and shortened the description, just need some direction on what you need for the `sourceUrl` field.

**Comment by KenticoDevTrev** [comment]
@rshackleton Kentico has been going the route of marketplace submissions be available on github, i would just throw your project on GIthub (make sure it's just the project itself and not the Kentico Instance).

http://devtrev.com/Trev-Tips-(Blog)/July-2019/Submitting-Components-to-Kentico-Marketplace

**Comment by giorgioLUK** [comment]
@rshackleton as @KenticoDevTrev mentioned (or as described here: https://github.com/Kentico/devnet.kentico.com#how-to-qualify) your project needs to utilize the open-source approach. Thank you!

**Comment by rshackleton** [comment]
@KenticoDevTrev @giorgioLUK thanks for the responses, I've poked people internally for their lack of ability to RTFM... We'll get something together ASAP and resubmit the entry.

For now feel free to close this PR!

(Sorry for wasting your time with this 🙄)

**Pull request closed without merging**
