### PR TITLE
adding marketplace contribution

### PR DESCRIPTION
**Pull request by IntegranetSam**

### CODE REVIEW

**Review by giorgioLUK — APPROVED** [review]
Hi @IntegranetSam, thank you for your contribution!

**Comment by IntegranetSam** [comment]
> Hi @IntegranetSam, thank you for your contribution!

Yay thanks! How long until it appears on the marketplace?

**Comment by IntegranetSam** [comment]
> Hi @IntegranetSam, thank you for your contribution!

@giorgioLUK What happens next? How do we merge with the master branch?

**Comment by IntegranetSam** [comment]
Hello? Can someone merge this?

**Review by giorgioLUK — CHANGES_REQUESTED** [review]
@IntegranetSam could you please adjust the "category" section? It fails because ["category" must be one of [module, webpart, website template, utility, mvc widget, mvc section, mvc form component, mvc inline editor, mvc personalization condition type, integration, other]].

Thank you!

**Comment by IntegranetSam** [comment]
> @IntegranetSam could you please adjust the "category" section? It fails because ["category" must be one of [module, webpart, website template, utility, mvc widget, mvc section, mvc form component, mvc inline editor, mvc personalization condition type, integration, other]].
> 
> Thank you!

@giorgioLUK Ahh okay wondered if that might have been the issue, should be all good now? Thanks!

**Review by giorgioLUK — APPROVED** [review]

**Review by giorgioLUK — APPROVED** [review]
It looks okay now!

**Pull request merged**
