### PR TITLE
Netconstruct menu module

### PR DESCRIPTION
**Pull request by chetanmistry**
Resubmission of NetConstruct's menus module. Believe we have addressed all the issues that were raised.

### CODE REVIEW

**Comment by chetanmistry** [comment]
> Thank you for the new submission Chetah! Could you please check thumbnailUrl? I was not able to open it - it looks like the file is corrupted. I would also recommend to add information about how the project is supported in case of bug to your README file (according to instructions described here: https://github.com/Kentico/devnet.kentico.com#how-to-qualify). Thank you!

Hi - we have addressed your issues - can you resubmit please.

**Comment by chetanmistry** [comment]
Thanks for the update. Is this approved now? Can you let me know what happens from here please.

Chetan Mistry
Development Director
T  +44 1937 581 123
http://www.netconstruct.co.uk<http://www.netconstruct.co.uk/>
twitter.com/NetConstruct<http://twitter.com/NetConstruct>

[green]

**Comment by chetanmistry** [comment]
@giorgioLUK although you say its ok - it looks like you have just closed the pull request without merging?

**Comment by giorgioLUK** [comment]
Build failed with the following error (https://travis-ci.com/Kentico/devnet.kentico.com/builds/130280350#L475): "description" length must be less than or equal to 160 characters long 

Could you please therefore adjust the length of your description?

**Comment by chetanmistry** [comment]
hi @giorgioLUK  - the description field has been reduced

**Pull request merged**
