### PR TITLE
New extension

### PR DESCRIPTION
**Pull request by sunandasoni**

### CODE REVIEW

**Comment by sunandasoni** [comment]
> Hi @sunandasoni, thank you for you contribution! However I can't approve your request since it do not meet our requirements described here: https://github.com/Kentico/devnet.kentico.com#how-to-qualify
> 
> Therefore please check these instructions and implement all of them in order to be able to submit your extension.
> 
> Thank you very much!

Hi ,

Actually I have to publish below extensions. And all file are there  https://github.com/sunandasoni/Kentico

{
    "name": "Avatar/User Picture upload & display",
    "description": "It upload & display picture of an user. We already have a webpart My Account in which have option to upload & display picture. But don't have individually webpart of it.",
    "thumbnailUrl": "https://github.com/sunandasoni/Kentico/blob/master/Systematix.png",
    "author": "Systematix infotech Pvt Ltd.",
    "sourceUrl": "https://github.com/sunandasoni/Kentico.git",
    "version": "1.0.0",
    "kenticoVersions": [
      "11.0.27"
    ],
    "category": "Webpart",
    "tags": ["Webpart", "Avatar", "User"]
  },

Could you please suggest how i can submit it and it's require any more details?

**Comment by giorgioLUK** [comment]
I believe that you are referring to the this: https://github.com/Kentico/devnet.kentico.com/pull/83

However as @makma mentioned in the comment: it looks like you accidentally submitted pull request to add-bingmaps branch, therefore we closed it (for submitting the new extension please follow these instructions: https://github.com/Kentico/devnet.kentico.com#registering-extensions). 

Regarding this submission, it is necessary to: 
- format readme.md
- include source code into repository as well (not only zip file)
- link/add documentatioon
- add info and decription of the project, what the extension/widget/webpart does
- add contribution guidelines (and link from readme)
- add licence iinformation (and link from readme)
- add info about support/related questions
-any screenshots in readme are highly appreciated

Thank you!

**Comment by sunandasoni** [comment]
> I believe that you are referring to the this: #83
> 
> However as @makma mentioned in the comment: it looks like you accidentally submitted pull request to add-bingmaps branch, therefore we closed it (for submitting the new extension please follow these instructions: https://github.com/Kentico/devnet.kentico.com#registering-extensions).
> 
> Regarding this submission, it is necessary to:
> 
> * format readme.md
> * include source code into repository as well (not only zip file)
> * link/add documentatioon
> * add info and decription of the project, what the extension/widget/webpart does
> * add contribution guidelines (and link from readme)
> * add licence iinformation (and link from readme)
> * add info about support/related questions
>   -any screenshots in readme are highly appreciated
> 
> Thank you!

Thanks for the response. I have updated details. can you please let me know if still wrong.

**Comment by sunandasoni** [comment]
close this.

**Pull request closed without merging**
