### PR TITLE
Add baseline sites

### PR DESCRIPTION
**Pull request by KenticoDevTrev**
Added Previous Kentico 12 Baseline Site, and new Kentico 13 .net Core 5.0 Baseline Site.  These sites provide starting points for development and provide common site tools and features.

### CODE REVIEW

**Review by giorgioLUK — CHANGES_REQUESTED** [review]
Hi Trevor, shouldn't be sourceURL for Kentico 12 Baseline different? Currently are both sourceURL identical. Thank you!

**Comment by KenticoDevTrev** [comment]
Woops! Good catch, updated, try now!

**Review by giorgioLUK — APPROVED** [review]

**Review by giorgioLUK — CHANGES_REQUESTED** [review]
One more thing, could you please adjust the "category" section, since it fails because "category" must be one of [module, webpart, website template, utility, mvc widget, mvc section, mvc form component, mvc inline editor, mvc personalization condition type, integration, other]. Thank you !

**Comment by KenticoDevTrev** [comment]
Sorry about that, i think i saw webpart and mixed it with website and just put "website", fixed to "website template"

**Review by giorgioLUK — APPROVED** [review]

**Pull request merged**
